server:
  port: 8080
plugins:
  fincaraiz:
    version: "v1.0"
    enabled: true 
  metrocuadrado:
    version: "v1.0" 
    enabled: true
  ciencuadras:
    version: "v1.0"   
    enabled: true    

  
